#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="/Users/rarojas/Documents/A_FULLAPP"
MODE="${1:-on}"
LOGFILE="${2:-/tmp/fullapp_perf.log}"
LAUNCH_BROWSER="${3:-TRUE}"

MODE_LC="$(printf "%s" "$MODE" | tr '[:upper:]' '[:lower:]')"
if [[ "$MODE_LC" != "on" && "$MODE_LC" != "off" ]]; then
  echo "Invalid mode: $MODE"
  echo "Usage: $0 [on|off] [/tmp/logfile.log] [TRUE|FALSE]"
  exit 1
fi

if [[ "$MODE_LC" == "on" ]]; then
  CACHE_HOMO="1"
  CACHE_ORTHO="1"
else
  CACHE_HOMO="0"
  CACHE_ORTHO="0"
fi

APP_HOMO_INITIAL_VISIBLE="${APP_HOMO_INITIAL_VISIBLE:-64}"
APP_ORTHO_INITIAL_VISIBLE="${APP_ORTHO_INITIAL_VISIBLE:-64}"
APP_ORTHO_ALIGNED_FAST="${APP_ORTHO_ALIGNED_FAST:-1}"
APP_FUTURE_MODE="${APP_FUTURE_MODE:-multisession}"
APP_FUTURE_WORKERS="${APP_FUTURE_WORKERS:-2}"
APP_ORTHO_LOOKUP_PARALLEL="${APP_ORTHO_LOOKUP_PARALLEL:-1}"
APP_ORTHO_LOOKUP_PARALLEL_MIN_JOBS="${APP_ORTHO_LOOKUP_PARALLEL_MIN_JOBS:-2}"
APP_ORTHO_LOCAL_PROGRESSIVE="${APP_ORTHO_LOCAL_PROGRESSIVE:-1}"
APP_ORTHO_RENDER_CHUNK_SIZE="${APP_ORTHO_RENDER_CHUNK_SIZE:-64}"
APP_ORTHO_AUTO_RENDER_MORE="${APP_ORTHO_AUTO_RENDER_MORE:-0}"
APP_ORTHO_AUTO_RENDER_DELAY_MS="${APP_ORTHO_AUTO_RENDER_DELAY_MS:-0}"
APP_ORTHO_SERVER_RENDER_NUDGE="${APP_ORTHO_SERVER_RENDER_NUDGE:-0}"
APP_ORTHO_SUSPEND_HIDDEN="${APP_ORTHO_SUSPEND_HIDDEN:-1}"
APP_HOMO_DEFER_SEQUENCE="${APP_HOMO_DEFER_SEQUENCE:-0}"
APP_ORTHO_DEFER_SEQUENCE="${APP_ORTHO_DEFER_SEQUENCE:-0}"
APP_FOOTER_DEFER_SEQUENCE="${APP_FOOTER_DEFER_SEQUENCE:-0}"
APP_DEFER_FEATURE_GC="${APP_DEFER_FEATURE_GC:-0}"
APP_HOMO_UPFRONT_ISOFORMS="${APP_HOMO_UPFRONT_ISOFORMS:-0}"
APP_ORTHO_UPFRONT_ISOFORMS="${APP_ORTHO_UPFRONT_ISOFORMS:-0}"

mkdir -p "$(dirname "$LOGFILE")"
cd "$ROOT_DIR"

echo "Mode: $MODE_LC"
echo "Log:  $LOGFILE"
echo "Defaults: APP_HOMO_INITIAL_VISIBLE=$APP_HOMO_INITIAL_VISIBLE APP_ORTHO_INITIAL_VISIBLE=$APP_ORTHO_INITIAL_VISIBLE"
echo "Aligned:  APP_ORTHO_ALIGNED_FAST=$APP_ORTHO_ALIGNED_FAST"
echo "Caches:   APP_HOMO_PLOT_CACHE=$CACHE_HOMO APP_ORTHO_PLOT_CACHE=$CACHE_ORTHO"
echo "Future:   APP_FUTURE_MODE=$APP_FUTURE_MODE APP_FUTURE_WORKERS=$APP_FUTURE_WORKERS"
echo "Ortho UI: APP_ORTHO_LOOKUP_PARALLEL=$APP_ORTHO_LOOKUP_PARALLEL APP_ORTHO_LOOKUP_PARALLEL_MIN_JOBS=$APP_ORTHO_LOOKUP_PARALLEL_MIN_JOBS APP_ORTHO_LOCAL_PROGRESSIVE=$APP_ORTHO_LOCAL_PROGRESSIVE APP_ORTHO_RENDER_CHUNK_SIZE=$APP_ORTHO_RENDER_CHUNK_SIZE APP_ORTHO_AUTO_RENDER_MORE=$APP_ORTHO_AUTO_RENDER_MORE APP_ORTHO_AUTO_RENDER_DELAY_MS=$APP_ORTHO_AUTO_RENDER_DELAY_MS APP_ORTHO_SERVER_RENDER_NUDGE=$APP_ORTHO_SERVER_RENDER_NUDGE"
echo "Render:   APP_ORTHO_SUSPEND_HIDDEN=$APP_ORTHO_SUSPEND_HIDDEN APP_HOMO_DEFER_SEQUENCE=$APP_HOMO_DEFER_SEQUENCE APP_ORTHO_DEFER_SEQUENCE=$APP_ORTHO_DEFER_SEQUENCE APP_FOOTER_DEFER_SEQUENCE=$APP_FOOTER_DEFER_SEQUENCE APP_DEFER_FEATURE_GC=$APP_DEFER_FEATURE_GC APP_HOMO_UPFRONT_ISOFORMS=$APP_HOMO_UPFRONT_ISOFORMS APP_ORTHO_UPFRONT_ISOFORMS=$APP_ORTHO_UPFRONT_ISOFORMS"
echo

APP_HOMO_PLOT_CACHE="$CACHE_HOMO" \
APP_ORTHO_PLOT_CACHE="$CACHE_ORTHO" \
APP_HOMO_INITIAL_VISIBLE="$APP_HOMO_INITIAL_VISIBLE" \
APP_ORTHO_INITIAL_VISIBLE="$APP_ORTHO_INITIAL_VISIBLE" \
APP_ORTHO_ALIGNED_FAST="$APP_ORTHO_ALIGNED_FAST" \
APP_FUTURE_MODE="$APP_FUTURE_MODE" \
APP_FUTURE_WORKERS="$APP_FUTURE_WORKERS" \
APP_ORTHO_LOOKUP_PARALLEL="$APP_ORTHO_LOOKUP_PARALLEL" \
APP_ORTHO_LOOKUP_PARALLEL_MIN_JOBS="$APP_ORTHO_LOOKUP_PARALLEL_MIN_JOBS" \
APP_ORTHO_LOCAL_PROGRESSIVE="$APP_ORTHO_LOCAL_PROGRESSIVE" \
APP_ORTHO_RENDER_CHUNK_SIZE="$APP_ORTHO_RENDER_CHUNK_SIZE" \
APP_ORTHO_AUTO_RENDER_MORE="$APP_ORTHO_AUTO_RENDER_MORE" \
APP_ORTHO_AUTO_RENDER_DELAY_MS="$APP_ORTHO_AUTO_RENDER_DELAY_MS" \
APP_ORTHO_SERVER_RENDER_NUDGE="$APP_ORTHO_SERVER_RENDER_NUDGE" \
APP_ORTHO_SUSPEND_HIDDEN="$APP_ORTHO_SUSPEND_HIDDEN" \
APP_HOMO_DEFER_SEQUENCE="$APP_HOMO_DEFER_SEQUENCE" \
APP_ORTHO_DEFER_SEQUENCE="$APP_ORTHO_DEFER_SEQUENCE" \
APP_FOOTER_DEFER_SEQUENCE="$APP_FOOTER_DEFER_SEQUENCE" \
APP_DEFER_FEATURE_GC="$APP_DEFER_FEATURE_GC" \
APP_HOMO_UPFRONT_ISOFORMS="$APP_HOMO_UPFRONT_ISOFORMS" \
APP_ORTHO_UPFRONT_ISOFORMS="$APP_ORTHO_UPFRONT_ISOFORMS" \
APP_PERF_TIMING=1 \
APP_DEBUG_LOGS=1 \
Rscript -e "shiny::runApp('.', launch.browser=$LAUNCH_BROWSER)" 2>&1 | tee "$LOGFILE"
