#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="/Users/rarojas/Documents/A_FULLAPP"
MODE="${1:-on}"
LOGFILE="${2:-/tmp/fullapp_perf.log}"
LAUNCH_BROWSER="${3:-TRUE}"

MODE_LC="$(printf "%s" "$MODE" | tr '[:upper:]' '[:lower:]')"
if [[ "$MODE_LC" != "on" && "$MODE_LC" != "off" ]]; then
  echo "Invalid mode: $MODE"
  echo "Usage: $0 [on|off] [/tmp/logfile.log] [TRUE|FALSE]"
  exit 1
fi

if [[ "$MODE_LC" == "on" ]]; then
  CACHE_HOMO="1"
  CACHE_ORTHO="1"
else
  CACHE_HOMO="0"
  CACHE_ORTHO="0"
fi

APP_HOMO_INITIAL_VISIBLE="${APP_HOMO_INITIAL_VISIBLE:-1}"
APP_ORTHO_INITIAL_VISIBLE="${APP_ORTHO_INITIAL_VISIBLE:-1}"
APP_ORTHO_ALIGNED_FAST="${APP_ORTHO_ALIGNED_FAST:-1}"
APP_ORTHO_ALIGNED_KMER_K="${APP_ORTHO_ALIGNED_KMER_K:-8}"

mkdir -p "$(dirname "$LOGFILE")"
cd "$ROOT_DIR"

echo "Mode: $MODE_LC"
echo "Log:  $LOGFILE"
echo "Defaults: APP_HOMO_INITIAL_VISIBLE=$APP_HOMO_INITIAL_VISIBLE APP_ORTHO_INITIAL_VISIBLE=$APP_ORTHO_INITIAL_VISIBLE"
echo "Aligned:  APP_ORTHO_ALIGNED_FAST=$APP_ORTHO_ALIGNED_FAST APP_ORTHO_ALIGNED_KMER_K=$APP_ORTHO_ALIGNED_KMER_K"
echo "Caches:   APP_HOMO_PLOT_CACHE=$CACHE_HOMO APP_ORTHO_PLOT_CACHE=$CACHE_ORTHO"
echo

APP_HOMO_PLOT_CACHE="$CACHE_HOMO" \
APP_ORTHO_PLOT_CACHE="$CACHE_ORTHO" \
APP_HOMO_INITIAL_VISIBLE="$APP_HOMO_INITIAL_VISIBLE" \
APP_ORTHO_INITIAL_VISIBLE="$APP_ORTHO_INITIAL_VISIBLE" \
APP_ORTHO_ALIGNED_FAST="$APP_ORTHO_ALIGNED_FAST" \
APP_ORTHO_ALIGNED_KMER_K="$APP_ORTHO_ALIGNED_KMER_K" \
APP_PERF_TIMING=1 \
APP_DEBUG_LOGS=1 \
Rscript -e "shiny::runApp('.', launch.browser=$LAUNCH_BROWSER)" 2>&1 | tee "$LOGFILE"
