args <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args, value = TRUE)
script_path <- if (length(file_arg)) sub("^--file=", "", file_arg[[1]]) else "scripts/test_plot_zoom_horizontal_only_static.R"
repo_root <- normalizePath(file.path(dirname(script_path), ".."), mustWork = TRUE)

zoom_js <- paste(readLines(file.path(repo_root, "www/js/plot_zoom.js"), warn = FALSE), collapse = "\n")
scss <- paste(readLines(file.path(repo_root, "custom.scss"), warn = FALSE), collapse = "\n")
compiled_css <- paste(readLines(file.path(repo_root, "www/css/cgv_compiled.css"), warn = FALSE), collapse = "\n")

stopifnot(grepl("function stableZoomHeight\\(item, wrapWidth, factor\\)", zoom_js))
stopifnot(grepl("function stableSvgZoomHeight\\(svg, fallbackHeight\\)", zoom_js))
stopifnot(grepl("function stableSvgZoomWidth\\(svg, factor\\)", zoom_js))
stopifnot(grepl("function effectiveViewBoxForHorizontalZoom\\(vb, viewportWidth, viewportHeight, preserveAspectRatio\\)", zoom_js))
stopifnot(grepl("function prepareSvgForHorizontalZoom\\(svg, factor, svgHeight\\)", zoom_js))
stopifnot(grepl("height: viewportHeight / uniformScale", zoom_js, fixed = TRUE))
stopifnot(grepl("y: vb.y - (offsetY / uniformScale)", zoom_js, fixed = TRUE))
stopifnot(grepl("var h = stableZoomHeight\\(items\\[i\\], wrapWidth, 1\\);", zoom_js))
stopifnot(grepl("var nh = stableZoomHeight\\(items\\[j\\], wrapWidth, factor\\);", zoom_js))
stopifnot(grepl("var svgHeight = stableSvgZoomHeight\\(svg, naturalH\\);", zoom_js))
stopifnot(grepl("svg\\.setAttribute\\('viewBox', effectiveViewBox\\);", zoom_js))
stopifnot(grepl("counterScaleDecorations\\(svg, baseStretchRatio \\* factor\\);", zoom_js))
stopifnot(grepl("height', svgHeight \\+ 'px', 'important'", zoom_js))
stopifnot(!grepl("svg\\.style\\.height = naturalH \\+ 'px'", zoom_js))
stopifnot(grepl("container.style.width = \\(factor \\* 100\\) \\+ '%';", zoom_js))
stopifnot(grepl("scale\\(' \\+ inv \\+ ',1\\)", zoom_js))
stopifnot(!grepl("scale\\(' \\+ inv \\+ ',' \\+ inv", zoom_js))

stopifnot(grepl("\\.plot-card-body \\.plot-card-main \\{[\\s\\S]*overflow: visible !important;", scss, perl = TRUE))
stopifnot(grepl("\\.plot-transcript-card \\.plot-card-body \\{[\\s\\S]*overflow: visible !important;", scss, perl = TRUE))
stopifnot(grepl("\\.plot-transcript-card \\.plot-card-body > \\.plot-card-footer \\{[\\s\\S]*position: relative;[\\s\\S]*flex: 0 0 30px;", scss, perl = TRUE))
stopifnot(grepl("\\.app-shell\\.compact-visual-mode \\.plot-transcript-card \\.plot-card-body > \\.plot-card-footer \\{[\\s\\S]*margin-top: -18px;", scss, perl = TRUE))
stopifnot(grepl("\\.plot-transcript-card \\.promoter-plot-container svg\\.ggiraph-svg,[\\s\\S]*min-height: 0 !important;[\\s\\S]*max-height: none !important;", scss, perl = TRUE))
stopifnot(grepl("\\.plot-transcript-card \\.plot-card-body > \\.plot-card-footer \\{[\\s\\S]*position: relative;[\\s\\S]*flex: 0 0 30px;", compiled_css, perl = TRUE))
stopifnot(grepl("\\.app-shell\\.compact-visual-mode \\.plot-transcript-card \\.plot-card-body > \\.plot-card-footer \\{[\\s\\S]*margin-top: -18px;", compiled_css, perl = TRUE))
stopifnot(grepl("\\.plot-transcript-card \\.promoter-plot-container svg\\.ggiraph-svg,[\\s\\S]*min-height: 0 !important;[\\s\\S]*max-height: none !important;", compiled_css, perl = TRUE))

cat("Plot zoom horizontal-only static checks passed.\n")
